public enum EventID
{

    NONE,
    //HOME SCRENE
    CHANGE_GEM = 49,
    CHANGE_COIN = 50,
    CHANGE_HEART = 51,
    CHANGE_AVATAR = 52,
    POPUP_OPENED = 53,
    POPUP_CLOSED = 54,
    BOOSTER_USE_REQUEST = 100,
    BOOSTER_CANCEL_REQUEST = 101,
    BOOSTER_BUY_REQUEST = 102,
    
    LEVEL_COMPLETE = 201,
    BOOSTER_DEACTIVATE_REQUEST = 205,

    // WE ARE WARRIORS
    HOUSE_DESTROYED = 206,  
    UNIT_DIED = 207,      
    FOOD_CHANGED = 208,    
    ON_CIV_CHANGED = 400,
    ON_EQUIPMENT_CHANGED = 401,

    ON_SKILL_CHANGED = 402,
    ON_ENEMY_WAVE_CHANGED = 403,
    ON_FOOD_UI_CHANGED = 404,

}
